### ISSUE TITLE
Add etcd certificates check

### ISSUE THREAD

**Issue by ebondare** [Tendrl/tendrl-ansible#111]
The installation playbook sets the nodes' configuration to
```
# Enable etcd SSL TLS cert based auth options
etcd_ca_cert_file: /etc/pki/tls/certs/ca-usmqe.crt
etcd_cert_file: /etc/pki/tls/certs/etcd.crt
etcd_key_file: /etc/pki/tls/private/etcd.key
```

But it doesn't check that these files actually exist. It would be nice to add that check.

**Comment by mbukatov** [comment]
See how rpm check is done, this one could be implemented in a similar way:

```
- name: Check if firewalld is installed                                         
  command: rpm -q firewalld                                                     
  register: rpm_q_firewalld                                                     
  changed_when: False                                                           
  failed_when: rpm_q_firewalld.rc > 1  

- name: Assert fail if firewalld is not installed and running                   
  assert:                                                                       
    that:                                                                       
      - rpm_q_firewalld.rc == 0   
    msg:
      - "tendrl-ansible did not complete execution as firewalld is not"
      - "installed, enabled nor running." 
```

Edit: you are right, [stat module](https://docs.ansible.com/ansible/latest/modules/stat_module.html) would be better than sheer command.
